name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup node.js
      # yarn cache is broken without corepack support.
      # Using forked version from https://github.com/actions/setup-node/pull/901
      uses: JP250552/setup-node@aa9724272b8a9ea9fca3d51295a2cc4707e35ec2
      with:
        node-version: 24
        cache: yarn
        corepack: true

    - name: Install dependencies
      run: yarn install --immutable

    - name: Run tests
      run: yarn test
